[packages]

[packages.dados-sigplan-planejamento]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-sigplan-planejamento-2025/main/datapackage.json"
"token" = "GITHUB_TOKEN"


[packages.dados-sisor-2024]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-sisor-2024/main/datapackage.json"
"token" = "GITHUB_TOKEN"